#!/bin/sh
# -----------------------------------------------------------------------------
# QNAP boot hook — installed on the DOM config partition (/dev/mmcblk0p6).
# Generated by install-autorun.sh; edit that, not this.
# -----------------------------------------------------------------------------
# QTS runs this from /tmp/config/autorun.sh very early in boot (init_nas.sh),
# and only when Control Panel -> Hardware -> "Run user defined processes during
# startup" is ticked. At that point the data volumes are usually not mounted
# yet, so everything real lives on /share and this only waits for it to appear.
#
# Backgrounded immediately: nothing here may block boot.
#
# NOTE: this file must live on the DOM. A drop in /etc/config/autorun.d/ is
# never executed by anything on this NAS — that directory is a dead end.
#
# The two paths below are placeholders; install-autorun.sh substitutes them
# with host-specific values before writing the file to the DOM. Running this
# copy directly (without installing) will not work — that is intentional.
# -----------------------------------------------------------------------------

PIHOLE_SCRIPT=__PIHOLE_WATCHDOG__
SWAP_SCRIPT=__SWAP_SCRIPT__
LOG=/tmp/autorun-boot.log
MAX_POLLS=150   # 150 x 2s = 5 min for the volumes to come up
RETRY_WAIT=15   # between failed attempts
PIHOLE_RETRIES=10  # 10 x 15s = 2.5 min of retries

run_when_ready() {
  target=$1
  label=$2
  retries=${3:-1}

  i=0
  while [ ! -x "$target" ] && [ "$i" -lt "$MAX_POLLS" ]; do
    sleep 2
    i=$((i + 1))
  done
  if [ ! -x "$target" ]; then
    echo "[$(date)] ${label}: gave up, ${target} never appeared" >> "$LOG"
    return 1
  fi
  echo "[$(date)] ${label}: found after $((i * 2))s, running" >> "$LOG"

  # This is the only shot at it — there is no periodic timer behind us — so a
  # transient early-boot failure (eth0 not up yet, Docker mid-start) must not
  # be final. The target is idempotent, so retrying costs nothing.
  attempt=1
  while : ; do
    if "$target" >> "$LOG" 2>&1; then
      echo "[$(date)] ${label}: ok on attempt ${attempt}" >> "$LOG"
      return 0
    fi
    if [ "$attempt" -ge "$retries" ]; then
      echo "[$(date)] ${label}: still failing after ${attempt} attempt(s) — giving up" >> "$LOG"
      return 1
    fi
    echo "[$(date)] ${label}: attempt ${attempt} failed, retrying in ${RETRY_WAIT}s" >> "$LOG"
    attempt=$((attempt + 1))
    sleep "$RETRY_WAIT"
  done
}

(
  echo "[$(date)] autorun.sh started (uptime $(cut -d. -f1 /proc/uptime)s)" > "$LOG"
  run_when_ready "$PIHOLE_SCRIPT" "pihole" "$PIHOLE_RETRIES"
  [ -e "$SWAP_SCRIPT" ] && run_when_ready "$SWAP_SCRIPT" "ssd-swap"
  echo "[$(date)] autorun.sh done" >> "$LOG"
) &

exit 0
