#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# Pi-hole bootstrap
# -----------------------------------------------------------------------------
# One-time prerequisite for the Pi-hole stack: creates the `macvlan_pihole`
# Docker network that docker-compose.yml references as `external: true`,
# then sets up a macvlan shim so the NAS host (and all Docker containers)
# can reach Pi-hole's LAN IP for DNS.
#
# Reads parameters from a sibling .env if present, else from process env.
# Required keys: PIHOLE_LAN_SUBNET, PIHOLE_LAN_GATEWAY, PIHOLE_PARENT_IFACE,
#                PIHOLE_IP, PIHOLE_SHIM_IP.
#
# PIHOLE_SHIM_IP: any unused IP on your LAN subnet (NOT PIHOLE_IP, NOT the
#                 gateway). Used only as the shim interface address so the
#                 host has a local leg on the macvlan. e.g. 192.168.1.253
#
# Idempotent: safe to re-run; existing network/shim are left untouched.
#
# Boot persistence: installs a launcher in /etc/config/autorun.d/ that invokes
# wait-pihole.sh on every boot. wait-pihole.sh waits for Docker + a healthy
# pihole container, then runs post-pihole.sh which (re)creates the shim and
# points /etc/resolv.conf at Pi-hole.
#
# Usage:
#   ./bootstrap.sh
# -----------------------------------------------------------------------------
set -euo pipefail

NETWORK_NAME="macvlan_pihole"
SHIM_IFACE="macvlan_shim0"
AUTORUN_DIR="/etc/config/autorun.d"
AUTORUN_FILE="${AUTORUN_DIR}/pihole-autorun.sh"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ -f "${SCRIPT_DIR}/../.env" ]]; then
  # shellcheck disable=SC1091
  set -a; . "${SCRIPT_DIR}/../.env"; set +a
fi

: "${PIHOLE_LAN_SUBNET:?PIHOLE_LAN_SUBNET must be set (see .env.example)}"
: "${PIHOLE_LAN_GATEWAY:?PIHOLE_LAN_GATEWAY must be set (see .env.example)}"
: "${PIHOLE_PARENT_IFACE:?PIHOLE_PARENT_IFACE must be set (see .env.example)}"
: "${PIHOLE_IP:?PIHOLE_IP must be set (see .env.example)}"
: "${PIHOLE_SHIM_IP:?PIHOLE_SHIM_IP must be set (see .env.example)}"

# -----------------------------------------------------------------------------
# 1. macvlan Docker network
# -----------------------------------------------------------------------------
if docker network inspect "${NETWORK_NAME}" >/dev/null 2>&1; then
  echo "Network '${NETWORK_NAME}' already exists — skipping."
else
  docker network create -d macvlan \
    --subnet="${PIHOLE_LAN_SUBNET}" \
    --gateway="${PIHOLE_LAN_GATEWAY}" \
    -o parent="${PIHOLE_PARENT_IFACE}" \
    "${NETWORK_NAME}" >/dev/null
  echo "Created macvlan network '${NETWORK_NAME}'" \
    "(subnet=${PIHOLE_LAN_SUBNET}, gw=${PIHOLE_LAN_GATEWAY}," \
    "parent=${PIHOLE_PARENT_IFACE})."
fi

# -----------------------------------------------------------------------------
# 2. Macvlan shim — lets the host reach PIHOLE_IP directly.
#    Without this, the host kernel drops traffic to its own macvlan children.
# -----------------------------------------------------------------------------
setup_shim() {
  if ip link show "${SHIM_IFACE}" >/dev/null 2>&1; then
    echo "Shim interface '${SHIM_IFACE}' already exists — skipping."
    return
  fi

  ip link add "${SHIM_IFACE}" link "${PIHOLE_PARENT_IFACE}" type macvlan mode bridge
  ip addr add "${PIHOLE_SHIM_IP}/32" dev "${SHIM_IFACE}"
  ip link set "${SHIM_IFACE}" up
  ip route add "${PIHOLE_IP}/32" dev "${SHIM_IFACE}"

  echo "Created macvlan shim '${SHIM_IFACE}'" \
    "(shim_ip=${PIHOLE_SHIM_IP}, route -> ${PIHOLE_IP})."
}

setup_shim

# -----------------------------------------------------------------------------
# 3. Boot persistence via autorun.d
#    Installs a tiny launcher that backgrounds wait-pihole.sh on every boot.
#    wait-pihole.sh waits for Docker + pihole to be healthy, then runs
#    post-pihole.sh (shim + /etc/resolv.conf). Running async avoids blocking
#    boot while we wait for the container to come up.
# -----------------------------------------------------------------------------
WAIT_SCRIPT="${SCRIPT_DIR}/wait-pihole.sh"
POST_SCRIPT="${SCRIPT_DIR}/post-pihole.sh"
for f in "${WAIT_SCRIPT}" "${POST_SCRIPT}"; do
  if [[ ! -f "${f}" ]]; then
    echo "Error: required script not found: ${f}" >&2
    exit 1
  fi
  chmod +x "${f}"
done

mkdir -p "${AUTORUN_DIR}"

cat > "${AUTORUN_FILE}" <<EOF
#!/bin/sh
# Auto-generated by bootstrap.sh — launches the Pi-hole wait/post pipeline.
# Do not edit manually; re-run bootstrap.sh to regenerate.
WAIT_SCRIPT="${WAIT_SCRIPT}"
[ -x "\${WAIT_SCRIPT}" ] && "\${WAIT_SCRIPT}" &
EOF

chmod +x "${AUTORUN_FILE}"
echo "Installed boot launcher at '${AUTORUN_FILE}' -> '${WAIT_SCRIPT}'."
