services:
  devbox:
    image: devbox:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: dev
        USER_UID: 1000
        USER_GID: 1000
    container_name: devbox
    hostname: devbox
    restart: unless-stopped
    ports:
      - "2222:22"
    dns:
      - ${LAN_DNS_IP}
    volumes:
      - ./home:/home/dev
      - ..:/projects
      - /share:/share
