#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# Pi-hole bootstrap
# -----------------------------------------------------------------------------
# One-time prerequisite for the Pi-hole stack: creates the `macvlan_pihole`
# Docker network that docker-compose.yml references as `external: true`,
# then sets up a macvlan shim so the NAS host (and all Docker containers)
# can reach Pi-hole's LAN IP for DNS.
#
# Reads parameters from a sibling .env if present, else from process env.
# Required keys: PIHOLE_LAN_SUBNET, PIHOLE_LAN_GATEWAY, PIHOLE_PARENT_IFACE,
#                PIHOLE_IP, PIHOLE_SHIM_IP.
#
# PIHOLE_SHIM_IP: any unused IP on your LAN subnet (NOT PIHOLE_IP, NOT the
#                 gateway). Used only as the shim interface address so the
#                 host has a local leg on the macvlan. e.g. 192.168.1.253
#
# Idempotent: safe to re-run; existing network/shim are left untouched.
#
# QNAP persistence: writes a script to /etc/config/autorun.d/ so the shim
# survives a NAS reboot (QTS does not have systemd).
#
# Usage:
#   ./bootstrap.sh
# -----------------------------------------------------------------------------
set -euo pipefail

NETWORK_NAME="macvlan_pihole"
SHIM_IFACE="macvlan_shim0"
AUTORUN_DIR="/etc/config/autorun.d"
AUTORUN_FILE="${AUTORUN_DIR}/pihole-macvlan-shim.sh"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ -f "${SCRIPT_DIR}/.env" ]]; then
  # shellcheck disable=SC1091
  set -a; . "${SCRIPT_DIR}/.env"; set +a
fi

: "${PIHOLE_LAN_SUBNET:?PIHOLE_LAN_SUBNET must be set (see .env.example)}"
: "${PIHOLE_LAN_GATEWAY:?PIHOLE_LAN_GATEWAY must be set (see .env.example)}"
: "${PIHOLE_PARENT_IFACE:?PIHOLE_PARENT_IFACE must be set (see .env.example)}"
: "${PIHOLE_IP:?PIHOLE_IP must be set (see .env.example)}"
: "${PIHOLE_SHIM_IP:?PIHOLE_SHIM_IP must be set (see .env.example)}"

# -----------------------------------------------------------------------------
# 1. macvlan Docker network
# -----------------------------------------------------------------------------
if docker network inspect "${NETWORK_NAME}" >/dev/null 2>&1; then
  echo "Network '${NETWORK_NAME}' already exists — skipping."
else
  docker network create -d macvlan \
    --subnet="${PIHOLE_LAN_SUBNET}" \
    --gateway="${PIHOLE_LAN_GATEWAY}" \
    -o parent="${PIHOLE_PARENT_IFACE}" \
    "${NETWORK_NAME}" >/dev/null
  echo "Created macvlan network '${NETWORK_NAME}'" \
    "(subnet=${PIHOLE_LAN_SUBNET}, gw=${PIHOLE_LAN_GATEWAY}," \
    "parent=${PIHOLE_PARENT_IFACE})."
fi

# -----------------------------------------------------------------------------
# 2. Macvlan shim — lets the host reach PIHOLE_IP directly.
#    Without this, the host kernel drops traffic to its own macvlan children.
# -----------------------------------------------------------------------------
setup_shim() {
  if ip link show "${SHIM_IFACE}" >/dev/null 2>&1; then
    echo "Shim interface '${SHIM_IFACE}' already exists — skipping."
    return
  fi

  ip link add "${SHIM_IFACE}" link "${PIHOLE_PARENT_IFACE}" type macvlan mode bridge
  ip addr add "${PIHOLE_SHIM_IP}/32" dev "${SHIM_IFACE}"
  ip link set "${SHIM_IFACE}" up
  ip route add "${PIHOLE_IP}/32" dev "${SHIM_IFACE}"

  echo "Created macvlan shim '${SHIM_IFACE}'" \
    "(shim_ip=${PIHOLE_SHIM_IP}, route -> ${PIHOLE_IP})."
}

setup_shim

# -----------------------------------------------------------------------------
# 3. QNAP persistence via autorun.d
#    QTS has no systemd. /etc/config/autorun.d/ scripts are executed by QTS
#    on every boot after networking is up.
# -----------------------------------------------------------------------------
mkdir -p "${AUTORUN_DIR}"

cat > "${AUTORUN_FILE}" <<EOF
#!/usr/bin/env bash
# Auto-generated by bootstrap.sh — restores the Pi-hole macvlan shim on boot.
# Do not edit manually; re-run bootstrap.sh to regenerate.
SHIM_IFACE="${SHIM_IFACE}"
PIHOLE_PARENT_IFACE="${PIHOLE_PARENT_IFACE}"
PIHOLE_SHIM_IP="${PIHOLE_SHIM_IP}"
PIHOLE_IP="${PIHOLE_IP}"

# Wait for parent interface to be ready
for i in $(seq 1 40); do
  ip link show "\${PIHOLE_PARENT_IFACE}" >/dev/null 2>&1 && break
  echo "Waiting for \${PIHOLE_PARENT_IFACE}... attempt ${i}"
  sleep 3
done

# Wait for Docker to be ready
for i in $(seq 1 40); do
  docker info >/dev/null 2>&1 && break
  echo "Waiting for Docker... attempt ${i}"
  sleep 3
done

if ! ip link show "\${SHIM_IFACE}" >/dev/null 2>&1; then
  ip link add "\${SHIM_IFACE}" link "\${PIHOLE_PARENT_IFACE}" type macvlan mode bridge
  ip addr add "\${PIHOLE_SHIM_IP}/32" dev "\${SHIM_IFACE}"
  ip link set "\${SHIM_IFACE}" up
  ip route add "\${PIHOLE_IP}/32" dev "\${SHIM_IFACE}"
fi

echo "nameserver \${PIHOLE_IP}" > /etc/resolv.conf
EOF

chmod +x "${AUTORUN_FILE}"
echo "Installed boot persistence at '${AUTORUN_FILE}'."

echo ""
echo "Bootstrap complete. Add to /etc/docker/daemon.json to use Pi-hole for all containers:"
echo "  { \"dns\": [\"${PIHOLE_IP}\", \"1.1.1.1\"] }"